// Code generated by a template
using System;


//using System;
using System.Collections.Generic;
using System.Linq;

namespace ADADB.Entities
{
    //**data source=localhost;initial catalog=ADADB;persist security info=True;user id=escritura;password=fourier;multipleactiveresultsets=True;App=EntityFramework

                   
       // AGRUPACIONES_BAJAS
          
                       
             // ID_ACTIVO_SAREB ( False )

                       
             // CODIGO_AGRUPACION ( False )

                       
             // TIPO_AGRUPACION ( False )

                       
             // USO_AGRUPACION ( False )

                       
             // TIPO_ACT_AGRUPACION ( False )

                       
             // RAIZ_COD ( False )

                       
             // CLAVE_AGRUPADORA ( False )

                       
             // TS_ALTA ( False )

          
           
                   
       // AGRUPACIONES_DM
          
                       
             // ID_ACTIVO_SAREB ( False )

                       
             // CODIGO_AGRUPACION ( False )

                       
             // TIPO_AGRUPACION ( False )

                       
             // USO_AGRUPACION ( False )

                       
             // TIPO_ACT_AGRUPACION ( False )

                       
             // RAIZ_COD ( False )

                       
             // ID_PROMCN_SAREB ( False )

                       
             // TIPO_SUELO ( False )

                       
             // CLAVE_AGRUPADORA ( False )

                       
             // ID_SECTOR ( False )

                       
             // IND_STATUS ( False )

                       
             // TIPO_ACTIVO ( False )

                       
             // ESTADO_GEN ( False )

                       
             // SUBTIPO_UNIFICADO ( False )

                       
             // SUBTIPO_DM ( False )

                       
             // USO_UNIFICADO ( False )

                       
             // USO_DOM_DM ( False )

                       
             // MUNICIPIO ( False )

                       
             // PROVINCIA ( False )

                       
             // FINCA_REGISTRAL ( False )

                       
             // IDUFIR ( False )

                       
             // REF_CATAST ( False )

                       
             // DES_SERVICER ( False )

                       
             // TERRITORIAL ( False )

                       
             // VNC ( False )

                       
             // FCH_DATOS ( False )

                       
             // TS_ALTA ( False )

                       
             // NUM_SUBCODIGO ( False )

                       
             // ORIGEN ( False )

                       
             // ID_JUICIO_EXPERTO ( False )

          
           
                   
       // AGRUPACIONES_RELA
          
                       
             // ID_AGRP_RELA ( False )

                       
             // ID_ACTIVO_SAREB ( False )

                       
             // CODIGO_AGRUPACION ( False )

                       
             // TIPO_AGRUPACION ( False )

                       
             // USO_AGRUPACION ( False )

                       
             // TIPO_ACT_AGRUPACION ( False )

                       
             // RAIZ_COD ( False )

                       
             // CLAVE_AGRUPADORA ( False )

                       
             // ID_JUICIO_EXPERTO ( False )

                       
             // FECHA_AUDIT ( False )

          
           
                   
       // PV_JUICIO_EXPERTO
          
                       
             // ID_ACTIVO_SAREB ( False )

                       
             // CODIGO_AGRUPACION ( False )

                       
             // TIPO_AGRUPACION ( False )

                       
             // USO_AGRUPACION ( False )

                       
             // TIPO_ACT_AGRUPACION ( False )

                       
             // RAIZ_COD ( False )

                       
             // CLAVE_AGRUPADORA ( False )

                       
             // NUM_SUBCODIGO ( False )

                       
             // ID_JUICIO_EXPERTO ( True )

                       
             // FECHA_AUDIT ( False )

                       
             // ACCION ( False )

                       
             // IND_STATUS ( False )

                       
             // IND_PROCESADO ( False )

          
           
                   
       // PV_JUICIO_EXPERTO_PRO
          
                       
             // ID_ACTIVO_SAREB ( False )

                       
             // CODIGO_AGRUPACION ( False )

                       
             // TIPO_AGRUPACION ( False )

                       
             // USO_AGRUPACION ( False )

                       
             // TIPO_ACT_AGRUPACION ( False )

                       
             // RAIZ_COD ( False )

                       
             // NUM_SUBCODIGO ( False )

                       
             // CLAVE_AGRUPADORA ( False )

          
           
                   
       // TBL_CARGAS_DM
          
                       
             // COD_ORIGEN_INFO ( True )

                       
             // FCH_DATOS ( False )

          
           
                   
       // asignacionAAFF
          
                       
             // IdActivo ( True )

                       
             // FcInicio ( True )

                       
             // FcFin ( False )

                       
             // IdServicerComercial ( False )

                       
             // IdModeloGestion ( False )

                       
             // IdPerimetroOperativo ( False )

                       
             // IdTerritorial ( False )

                       
             // CodSituacion ( False )

                       
             // CodUsuarioAudit ( False )

                       
             // FechaAudit ( False )

          
           
                   
       // asignacionAAII
          
                       
             // IdActivo ( True )

                       
             // FcInicio ( True )

                       
             // FcFin ( False )

                       
             // IdServicerComercial ( False )

                       
             // IdModeloGestion ( False )

                       
             // IdPerimetroOperativo ( False )

                       
             // IdTerritorial ( False )

                       
             // CodSituacion ( False )

                       
             // CodUsuarioAudit ( False )

                       
             // FechaAudit ( False )

          
           
                   
       // HIST_AsignacionAAFF
          
                       
             // Id ( True )

                       
             // IdActivo ( False )

                       
             // FechaInicio ( False )

                       
             // FechaFin ( False )

                       
             // IdServicerComercial ( False )

                       
             // IdModeloGestion ( False )

                       
             // IdPerimetroOperativo ( False )

                       
             // IdTerritorial ( False )

                       
             // CodUsuarioAudit ( False )

                       
             // FechaHoraAudit ( False )

          
           
                   
       // HIST_AsignacionAAII
          
                       
             // Id ( True )

                       
             // IdActivo ( False )

                       
             // FechaInicio ( False )

                       
             // FechaFin ( False )

                       
             // IdServicerComercial ( False )

                       
             // IdModeloGestion ( False )

                       
             // IdPerimetroOperativo ( False )

                       
             // IdTerritorial ( False )

                       
             // CodUsuarioAudit ( False )

                       
             // FechaHoraAudit ( False )

          
           
                   
       // SolCambio
          
                       
             // Id ( True )

                       
             // TipoActivo ( False )

                       
             // IdModeloGestion ( False )

                       
             // IdServicerComercial ( False )

                       
             // IdPerimetroOper ( False )

                       
             // IdTerritorial ( False )

                       
             // FcInicio ( False )

                       
             // FcIniProceso ( False )

                       
             // FcFinProceso ( False )

                       
             // IdValidacion ( False )

                       
             // UserAudit ( False )

          
           
                   
       // Validacion
          
                       
             // IdPeticionCambio ( True )

                       
             // IdActivo ( True )

                       
             // IdValidacion ( False )

                       
             // FcAudit ( False )

          
           
               
                   
       // EstrategiaAACC
          
                       
             // IdActivo ( True )

                       
             // FcInicio ( True )

                       
             // FcFin ( False )

                       
             // IdEstrategia ( False )

                       
             // CodSituacion ( False )

                       
             // CodUsuarioAudit ( False )

                       
             // FechaAudit ( False )

          
           
                   
       // EstrategiaAAFF
          
                       
             // IdActivo ( True )

                       
             // FcInicio ( True )

                       
             // FcFin ( False )

                       
             // IdEstrategia ( False )

                       
             // CodSituacion ( False )

                       
             // CodUsuarioAudit ( False )

                       
             // FechaAudit ( False )

          
           
                   
       // EstrategiaAAII
          
                       
             // IdActivo ( True )

                       
             // FcInicio ( True )

                       
             // FcFin ( False )

                       
             // IdEstrategia ( False )

                       
             // CodSituacion ( False )

                       
             // CodUsuarioAudit ( False )

                       
             // FechaAudit ( False )

          
           
                   
       // HIST_EstrategiaAACC
          
                       
             // Id ( True )

                       
             // IdActivo ( False )

                       
             // FcInicio ( False )

                       
             // FcFin ( False )

                       
             // IdEstrategia ( False )

                       
             // CodUsuarioAudit ( False )

                       
             // FechaAudit ( False )

          
           
                   
       // HIST_EstrategiaAAFF
          
                       
             // Id ( True )

                       
             // IdActivo ( False )

                       
             // FcInicio ( False )

                       
             // FcFin ( False )

                       
             // IdEstrategia ( False )

                       
             // CodUsuarioAudit ( False )

                       
             // FechaAudit ( False )

          
           
                   
       // HIST_EstrategiaAAII
          
                       
             // Id ( True )

                       
             // IdActivo ( False )

                       
             // FcInicio ( False )

                       
             // FcFin ( False )

                       
             // IdEstrategia ( False )

                       
             // CodUsuarioAudit ( False )

                       
             // FechaAudit ( False )

          
           
                   
       // SolCambioEstrategia
          
                       
             // Id ( True )

                       
             // TipoActivo ( False )

                       
             // IdEstrategia ( False )

                       
             // FcInicio ( False )

                       
             // FcIniProceso ( False )

                       
             // FcFinProceso ( False )

                       
             // UserAudit ( False )

          
           
                   
       // ValidacionEstrategia
          
                       
             // IdCambioEstrategia ( True )

                       
             // IdActivo ( True )

                       
             // IdValidacion ( False )

                       
             // FcAudit ( False )

          
           
                   
       // HIST_TipologiaGestionAACC
          
                       
             // Id ( True )

                       
             // IdActivo ( False )

                       
             // FcInicio ( False )

                       
             // FcFin ( False )

                       
             // CodEstadoGeneralGest ( False )

                       
             // CodUsoDominanteGest ( False )

                       
             // CodSubTipoActivoGest ( False )

                       
             // CodCategoriaSueloGest ( False )

                       
             // CodUsuarioAudit ( False )

                       
             // FechaAudit ( False )

          
           
                   
       // HIST_TipologiaGestionAAII
          
                       
             // Id ( True )

                       
             // IdActivo ( False )

                       
             // FcInicio ( False )

                       
             // FcFin ( False )

                       
             // CodEstadoGeneralGest ( False )

                       
             // CodUsoDominanteGest ( False )

                       
             // CodSubTipoActivoGest ( False )

                       
             // CodCategoriaSueloGest ( False )

                       
             // CodUsuarioAudit ( False )

                       
             // FechaAudit ( False )

          
           
                   
       // SolCambioTipologia
          
                       
             // Id ( True )

                       
             // TipoActivo ( False )

                       
             // CodEstadoGeneralGest ( False )

                       
             // CodUsoDominanteGest ( False )

                       
             // CodSubTipoActivoGest ( False )

                       
             // CodCategoriaSueloGest ( False )

                       
             // FcInicio ( False )

                       
             // FcInitProceso ( False )

                       
             // FcFinProceso ( False )

                       
             // UserAudit ( False )

          
           
                   
       // TipologiaGestionAACC
          
                       
             // IdActivo ( True )

                       
             // FcInicio ( True )

                       
             // FcFin ( False )

                       
             // CodEstadoGeneralGest ( False )

                       
             // CodUsoDominanteGest ( False )

                       
             // CodSubTipoActivoGest ( False )

                       
             // CodCategoriaSueloGest ( False )

                       
             // CodUsuarioAudit ( False )

                       
             // FechaAudit ( False )

          
           
                   
       // TipologiaGestionAAII
          
                       
             // IdActivo ( True )

                       
             // FcInicio ( True )

                       
             // FcFin ( False )

                       
             // CodEstadoGeneralGest ( False )

                       
             // CodUsoDominanteGest ( False )

                       
             // CodSubTipoActivoGest ( False )

                       
             // CodCategoriaSueloGest ( False )

                       
             // CodUsuarioAudit ( False )

                       
             // FechaAudit ( False )

          
           
                   
       // ValidacionTipologiaGestion
          
                       
             // IdCambioTipologiaGest ( True )

                       
             // IdActivo ( True )

                       
             // IdValidacion ( False )

                       
             // FechaAudit ( False )

          
           
                   
       // log
          
                       
             // Id ( True )

                       
             // FECHA ( False )

                       
             // PROCESO ( False )

                       
             // ESTADO ( False )

                       
             // Descripcion ( False )

          
           
                   
       // ActivoMarca
          
                       
             // IdActivo ( True )

                       
             // IdPerimetro ( True )

                       
             // CodTipoActivo ( True )

                       
             // FechaMarcado ( False )

                       
             // FechaFin ( False )

                       
             // CodUsuarioAudit ( False )

                       
             // IdCargaPerimetro ( False )

          
           
                   
       // CargaPerimetro
          
                       
             // Id ( True )

                       
             // IdPerimetro ( False )

                       
             // CodUsuarioCarga ( False )

                       
             // FechaHoraCarga ( False )

                       
             // CodTipoActivo ( False )

                       
             // FechaFin ( False )

                       
             // EsCargaIncremental ( False )

                       
             // FechaHoraMarcado ( False )

                       
             // EstadoNotificacion ( False )

          
           
                   
       // HIST_ActivoMarca
          
                       
             // Id ( True )

                       
             // IdActivo ( False )

                       
             // IdPerimetro ( False )

                       
             // CodtipoActivo ( False )

                       
             // FechaMarcado ( False )

                       
             // FechaFin ( False )

                       
             // CodUsuarioAudit ( False )

                       
             // IdCargaPerimetro ( False )

                       
             // FechaHoraAudit ( False )

          
           
                   
       // Perimetro
          
                       
             // Id ( True )

                       
             // CodMarca ( False )

                       
             // Descripcion ( False )

                       
             // DescripcionLarga ( False )

                       
             // IdSubTipoPerimetro ( False )

                       
             // IdNivelBloqueo ( False )

                       
             // IdAreaResponsable ( False )

                       
             // AplicaAAII ( False )

                       
             // AplicaAAFF ( False )

                       
             // AplicaAACC ( False )

                       
             // PermiteCargaIncremental ( False )

                       
             // FechaAlta ( False )

                       
             // CodUsuarioAudit ( False )

                       
             // FechaHoraAudit ( False )

                       
             // CodSituacion ( False )

                       
             // EsHeredable ( False )

                       
             // FechaFin ( False )

          
           
                   
       // ValidacionPerimetro
          
                       
             // IdActivo ( True )

                       
             // IdCargaPerimetro ( True )

                       
             // IdValidacion ( False )

          
           
                   
       // DM_POSICION_AACC_TB
          
                       
             // ID_ACTIVO_SAREB ( True )

                       
             // FCH_CIERRE_DT ( True )

                       
             // FCH_ALTA ( False )

                       
             // FCH_BAJA ( False )

                       
             // COD_SERVICER ( False )

                       
             // DES_SERVICER ( False )

                       
             // ID_REF_CATAST ( False )

                       
             // ID_IDUFIR ( False )

                       
             // ID_FIN_REG ( False )

                       
             // NUM_REG ( False )

                       
             // COD_PROVNC_REG ( False )

                       
             // DES_PROVNC_REG ( False )

                       
             // COD_MUNICP_REG ( False )

                       
             // DES_MUNICP_REG ( False )

                       
             // COD_COMUNI_AUTO ( False )

                       
             // DES_COMUNI_AUTO ( False )

                       
             // NOMB_REG ( False )

                       
             // ID_SUBFIN_REG ( False )

                       
             // COD_TIPO_GTIA ( False )

                       
             // DES_TIPO_GTIA ( False )

                       
             // COD_TIPO_ACT_AACC ( False )

                       
             // DES_TIPO_ACT_AACC ( False )

                       
             // COD_PAIS ( False )

                       
             // DES_PAIS ( False )

                       
             // COD_PROVNC ( False )

                       
             // DES_PROVNC ( False )

                       
             // COD_MUNICP ( False )

                       
             // DES_MUNICP ( False )

                       
             // DES_POBLCN ( False )

                       
             // COD_TIPO_VIA ( False )

                       
             // DES_TIPO_VIA ( False )

                       
             // DES_NOMBRE_VIA ( False )

                       
             // NUM_VIA ( False )

                       
             // NUM_VIA_L ( False )

                       
             // NUM_VIA_2 ( False )

                       
             // NUM_VIA_2_L ( False )

                       
             // DES_BLOQUE ( False )

                       
             // DES_PUERTA ( False )

                       
             // DES_ESCALERA ( False )

                       
             // NUM_COD_POSTAL ( False )

                       
             // DES_PLANTA ( False )

                       
             // IMP_GTIA ( False )

                       
             // IND_STATUS ( False )

                       
             // TS_ALTA ( False )

                       
             // ESCALERA ( False )

                       
             // COD_CL_USO_DOM ( False )

                       
             // DES_CL_USO_DOM ( False )

                       
             // COD_SUBTIP_AAII_SAREB ( False )

                       
             // DES_SUBTIP_AAII_SAREB ( False )

                       
             // COD_ESTADO_GEN ( False )

                       
             // DES_ESTADO_GEN ( False )

                       
             // COD_CATEG_SUELO ( False )

                       
             // ID_ACTIVO_REF_DUP ( False )

                       
             // COD_TIPO_ORIGEN ( False )

          
           
                   
       // DM_POSICION_AAFF_TB
          
                       
             // ID_ACTIVO_SAREB ( True )

                       
             // FCH_CIERRE_DT ( True )

                       
             // FCH_ALTA ( False )

                       
             // FCH_BAJA ( False )

                       
             // ID_ENTIDD ( False )

                       
             // DES_ENTIDD ( False )

                       
             // COD_RENDIM ( False )

                       
             // DES_RENDIM ( False )

                       
             // ID_SUCU ( False )

                       
             // NUM_NCTA ( False )

                       
             // COD_SERVICER ( False )

                       
             // DES_SERVICER ( False )

                       
             // IMP_PT_CESION ( False )

                       
             // IMP_PT ( False )

                       
             // COD_TIPO_INTERV ( False )

                       
             // IND_STATUS ( False )

                       
             // TS_ALTA ( False )

          
           
                   
       // DM_POSICION_AAII_TB
          
                       
             // ID_ACTIVO_SAREB ( True )

                       
             // FCH_CIERRE_DT ( True )

                       
             // FCH_ALTA ( False )

                       
             // FCH_BAJA ( False )

                       
             // COD_SERVICER ( False )

                       
             // DES_SERVICER ( False )

                       
             // ID_REF_CATAST ( False )

                       
             // DES_TOMO ( False )

                       
             // DES_LIBRO ( False )

                       
             // ID_IDUFIR ( False )

                       
             // ID_FIN_REG ( False )

                       
             // NUM_REG ( False )

                       
             // ID_SUBFIN_REG ( False )

                       
             // COD_REG_UNIVOC ( False )

                       
             // COD_PROVNC_REG ( False )

                       
             // DES_PROVNC_REG ( False )

                       
             // COD_MUNICP_REG ( False )

                       
             // DES_MUNICP_REG ( False )

                       
             // COD_TIPO_AAII ( False )

                       
             // DES_TIPO_AAII ( False )

                       
             // COD_SUBTIPO_AAII ( False )

                       
             // DES_SUBTIPO_AAII ( False )

                       
             // COD_PAIS ( False )

                       
             // DES_PAIS ( False )

                       
             // COD_PROVNC ( False )

                       
             // DES_PROVNC ( False )

                       
             // COD_COMUNI_AUTO ( False )

                       
             // DES_COMUNI_AUTO ( False )

                       
             // COD_MUNICP ( False )

                       
             // DES_MUNICP ( False )

                       
             // DES_POBLCN ( False )

                       
             // COD_TIPO_VIA ( False )

                       
             // DES_TIPO_VIA ( False )

                       
             // DES_NOMBRE_VIA ( False )

                       
             // NUM_VIA ( False )

                       
             // DES_BLOQUE ( False )

                       
             // DES_PUERTA ( False )

                       
             // NUM_COD_POSTAL ( False )

                       
             // DES_PLANTA ( False )

                       
             // IMP_PT ( False )

                       
             // IMP_PT_CES ( False )

                       
             // IND_STATUS ( False )

                       
             // TS_ALTA ( False )

                       
             // COD_SUBTIP_AAII_SAREB ( False )

                       
             // DES_SUBTIP_AAII_SAREB ( False )

                       
             // COD_ESTADO_GEN ( False )

                       
             // DES_ESTADO_GEN ( False )

                       
             // COD_CATEG_SUELO ( False )

                       
             // ID_PROMCN_SAREB ( False )

                       
             // ESCALERA ( False )

                       
             // COD_CL_USO_DOM ( False )

                       
             // DES_TERRITORIAL ( False )

                       
             // DES_CL_USO_DOM ( False )

                       
             // COD_TIPO_ORIGEN ( False )

          
           
                   
       // DM_POSICION_INTERVINIENTES_TB
          
                       
             // ID_INTERV ( True )

                       
             // ID_SERV ( True )

                       
             // FCH_CIERRE_DT ( True )

                       
             // ID_IDEN ( False )

                       
             // COD_TIPO_IDEN ( False )

                       
             // DES_TIPO_IDEN ( False )

                       
             // DES_NOMBRE ( False )

                       
             // DES_APELLD_1 ( False )

                       
             // DES_APELLD_2 ( False )

                       
             // COD_TIPO_VIA ( False )

                       
             // DES_TIPO_VIA ( False )

                       
             // DES_NOMBRE_VIA ( False )

                       
             // NUM_VIA ( False )

                       
             // NUM_BLOQUE_PORTAL ( False )

                       
             // NUM_ESCA ( False )

                       
             // NUM_PLANTA ( False )

                       
             // NUM_PUERTA ( False )

                       
             // NUM_COD_POSTAL ( False )

                       
             // DES_LOCALD ( False )

                       
             // COD_MUNICP ( False )

                       
             // DES_MUNICP ( False )

                       
             // COD_PROVNC ( False )

                       
             // DES_PROVNC ( False )

                       
             // COD_COMAUT ( False )

                       
             // DES_COMAUT ( False )

                       
             // COD_PAIS ( False )

                       
             // DES_PAIS ( False )

                       
             // ID_GRUPO_RIESGO ( False )

                       
             // DES_NOMBRE_GRUPO ( False )

                       
             // IND_STATUS ( False )

                       
             // TS_ALTA ( False )

                       
             // COD_TIPO_PERSON_JURIDIC ( False )

                       
             // DES_TIPO_PERSON_JURIDIC ( False )

                       
             // IND_GRND_ACREDT_GSTION_DIRECT ( False )

                       
             // FCH_ALTA ( False )

                       
             // FCH_BAJA ( False )

          
           
                   
       // DM_POSICION_SUELO_TB
          
                       
             // ID_ACTIVO ( False )

                       
             // FCH_CIERRE_DT ( False )

                       
             // ID_SECTOR ( False )

                       
             // TS_ALTA ( False )

          
           
                   
       // DM_RELA_ACTIVO_GARANTIAS_TB
          
                       
             // ID_ACTIVO ( True )

                       
             // ID_ACTIVO_GTIA ( True )

                       
             // FCH_CIERRE_DT ( True )

                       
             // COD_TIPO_GTIA ( False )

                       
             // DES_TIPO_GTIA ( False )

                       
             // IND_STATUS ( False )

                       
             // TS_ALTA ( False )

          
           
                   
       // DM_RELA_ACTIVO_INTERVINIENTE_TB
          
                       
             // ID_INTERV ( True )

                       
             // ID_ACTIVO ( True )

                       
             // COD_TIPO_RELA_ACTINT ( True )

                       
             // FCH_CIERRE_DT ( True )

                       
             // DES_TIPO_RELA_ACTINT ( False )

                       
             // ID_IDEN ( False )

                       
             // COD_TIPO_TITULR ( False )

                       
             // DES_TIPO_TITULR ( False )

                       
             // NUM_ORDEN_INTERV ( False )

                       
             // IND_STATUS ( False )

                       
             // TS_ALTA ( False )

          
           
                   
       // PV_MAESTRO_CODIGOS
          
                       
             // USO_AGRUPACION ( False )

                       
             // CLAVE_AGRUPADORA ( False )

                       
             // CODIGO_AGRUPACION ( False )

                       
             // IND_SUELO ( False )

                       
             // RAIZ_COD ( False )

                       
             // ORIGEN ( False )

                       
             // TS_ALTA ( False )

          
           
                   
       // AreaResponsable
          
                       
             // Id ( True )

                       
             // Nombre ( False )

                       
             // Buzon ( False )

                       
             // FechAlta ( False )

                       
             // CodUsuarioAudit ( False )

          
           
                   
       // Estrategia
          
                       
             // Id ( True )

                       
             // CodEstrategia ( False )

                       
             // Descripcion ( False )

                       
             // AplicaAAII ( False )

                       
             // AplicaAAFF ( False )

                       
             // AplicaAACC ( False )

                       
             // userAudit ( False )

                       
             // fechaAlta ( False )

                       
             // IdPerimetroAutomatico ( False )

                       
             // AplicaEstrategiasRepetidas ( False )

          
           
                   
       // HIST_AreaResponsable
          
                       
             // Id ( True )

                       
             // IdAreaResponsable ( False )

                       
             // Descripcion ( False )

                       
             // Buzon ( False )

                       
             // CodUsuarioAudit ( False )

                       
             // FechaAlta ( False )

                       
             // FechaBaja ( False )

          
           
                   
       // HIST_ModeloGestion
          
                       
             // Id ( True )

                       
             // IdModeloGestion ( False )

                       
             // CodModeloGestion ( False )

                       
             // Descripcion ( False )

                       
             // userAudit ( False )

                       
             // fechaAlta ( False )

                       
             // fechaBaja ( False )

          
           
                   
       // HIST_NivelBloqueo
          
                       
             // Id ( True )

                       
             // IdNivelBloqueo ( False )

                       
             // CodNivelBloqueo ( False )

                       
             // Descripcion ( False )

                       
             // CodUsuarioAudit ( False )

                       
             // FechaAlta ( False )

                       
             // FechaBaja ( False )

          
           
                   
       // HIST_Perimetro
          
                       
             // Id ( True )

                       
             // IdPerimetro ( False )

                       
             // CodMarca ( False )

                       
             // Descripcion ( False )

                       
             // DescripcionLarga ( False )

                       
             // IdSubtipoPerimetro ( False )

                       
             // IdNivelBloqueo ( False )

                       
             // IdAreaResponsable ( False )

                       
             // AplicaAAII ( False )

                       
             // AplicaAAFF ( False )

                       
             // AplicaAACC ( False )

                       
             // PermiteCargaIncremental ( False )

                       
             // CodUsuarioAudit ( False )

                       
             // FechaAlta ( False )

                       
             // FechaBaja ( False )

          
           
                   
       // HIST_PerimetroOperativo
          
                       
             // Id ( True )

                       
             // IdPerimetro ( False )

                       
             // CodPerimetro ( False )

                       
             // Descripcion ( False )

                       
             // userAudit ( False )

                       
             // fechaAlta ( False )

                       
             // fechaBaja ( False )

          
           
                   
       // HIST_ServicerComercial
          
                       
             // Id ( True )

                       
             // IdServicer ( False )

                       
             // CodServicer ( False )

                       
             // Descripcion ( False )

                       
             // userAudit ( False )

                       
             // fechaAlta ( False )

                       
             // fechaBaja ( False )

          
           
                   
       // HIST_subtipoPerimetro
          
                       
             // Id ( True )

                       
             // IdSubtipoperimetro ( False )

                       
             // Descripcion ( False )

                       
             // IdTipoPerimetro ( False )

                       
             // CodUsuarioAudit ( False )

                       
             // FechaAlta ( False )

                       
             // FechaBaja ( False )

          
           
                   
       // HIST_TerritorialUbicacion
          
                       
             // Id ( True )

                       
             // IdTerritorial ( False )

                       
             // CodTerritorialUbicacion ( False )

                       
             // Descripcion ( False )

                       
             // userAudit ( False )

                       
             // fechaAlta ( False )

                       
             // fechaBaja ( False )

          
           
                   
       // HIST_UbicacionProvincia
          
                       
             // Id ( True )

                       
             // IdProvincia ( False )

                       
             // CodProvincia ( False )

                       
             // Descripcion ( False )

                       
             // IdUbicacion ( False )

                       
             // userAudit ( False )

                       
             // fechaAlta ( False )

                       
             // fechaBaja ( False )

          
           
                   
       // HIST_Usuario
          
                       
             // CodUsuario ( True )

                       
             // FechaHoraAudit ( True )

                       
             // Nombre ( False )

                       
             // email ( False )

                       
             // IdRol ( False )

                       
             // FechaAlta ( False )

                       
             // FechaBaja ( False )

                       
             // CodUsuarioAudit ( False )

          
           
                   
       // MarcasAutomaticas
          
                       
             // Id ( True )

                       
             // CodEstrategia ( False )

                       
             // CodMarca ( False )

                       
             // EsAutomatico ( False )

                       
             // EsExcepcion ( False )

                       
             // userAudit ( False )

                       
             // fechaAlta ( False )

                       
             // AplicaEstrategiasRepetidas ( False )

          
           
                   
       // ModeloGestion
          
                       
             // Id ( True )

                       
             // CodModeloGestion ( False )

                       
             // Descripcion ( False )

                       
             // userAudit ( False )

                       
             // fechaAlta ( False )

          
           
                   
       // MsgValidacion
          
                       
             // Id ( True )

                       
             // Validacion ( False )

                       
             // Mensaje ( False )

          
           
                   
       // NivelBloqueo
          
                       
             // Id ( True )

                       
             // CodNivelBlq ( False )

                       
             // Descripcion ( False )

                       
             // FechAlta ( False )

                       
             // CodUsuarioAudit ( False )

          
           
                   
       // PerimetroOperativo
          
                       
             // Id ( True )

                       
             // CodPerimetro ( False )

                       
             // Descripcion ( False )

                       
             // userAudit ( False )

                       
             // fechaAlta ( False )

          
           
                   
       // RelaUsuarioRol
          
                       
             // IdRol ( True )

                       
             // CodUsuario ( True )

                       
             // FechaAlta ( False )

                       
             // CodUsuarioAudit ( False )

          
           
                   
       // Rol
          
                       
             // Id ( True )

                       
             // CodRol ( False )

                       
             // Nombre ( False )

                       
             // FechaAlta ( False )

                       
             // CodUsuarioAudit ( False )

          
           
                   
       // ServicerComercial
          
                       
             // Id ( True )

                       
             // CodServicer ( False )

                       
             // Descripcion ( False )

                       
             // userAudit ( False )

                       
             // fechaAlta ( False )

          
           
                   
       // SubTipoPerimetro
          
                       
             // Id ( True )

                       
             // Descripcion ( False )

                       
             // IdTipoPerimetro ( False )

                       
             // FechaAlta ( False )

                       
             // UserAudit ( False )

          
           
                   
       // TerritorialForzada
          
                       
             // IdActivo ( True )

                       
             // IdTerritorial ( False )

                       
             // FechaAudit ( False )

          
           
                   
       // TerritorialUbicacion
          
                       
             // Id ( True )

                       
             // CodTerritorialUbicacion ( False )

                       
             // Descripcion ( False )

                       
             // userAudit ( False )

                       
             // fechaAlta ( False )

                       
             // FechaHoraAudit ( False )

          
           
                   
       // TipoPerimetro
          
                       
             // Id ( True )

                       
             // Descripcion ( False )

                       
             // FechaAlta ( False )

                       
             // UserAudit ( False )

                       
             // FechaHoraAudit ( False )

          
           
                   
       // UbicacionProvincia
          
                       
             // Id ( True )

                       
             // CodProvincia ( False )

                       
             // Descripcion ( False )

                       
             // IdUbicacion ( False )

                       
             // userAudit ( False )

                       
             // fechaAlta ( False )

          
           
                   
       // Usuario
          
                       
             // Id ( True )

                       
             // CodUsuario ( False )

                       
             // Nombre ( False )

                       
             // email ( False )

                       
             // FechaAlta ( False )

                       
             // CodUsuarioAudit ( False )

          
           
    
}

